function PrintOutput(iTemp, count, cumcases, fileID)
        % Input: - iTemp: Time [days]
        %        - count: Number of people in each population
        %        - cumcases: Cumulative number of cases
        %        - fileID: Reference to output file
        %
        % Print in a text file referenced by fileID population count at given time step
    fprintf(fileID,'%8.2d %8.2d %8.2d %8.2d %8.2d %8.2d %8.2d %8.2d %8.2d\n',iTemp, ...
            count(1), ...
            count(2), ...
            count(3), ...
            count(4), ...
            count(5), ...
            count(6), ...
            count(7), ...
            cumcases);
end